### PR TITLE
Add some assets to simplify dev

### PR DESCRIPTION
**Pull request by Nemikolh**
This assets will be removed in the future, once we have the assets infrastructure in place.
@Vaelden : Would you mind checking you've got all the one you wanted?

Feel free to merge once you are happy! :smiley:

### CODE REVIEW

**Comment by lthms** [comment]
We should add a file that explicitely says we do not own this materiel and plan to use something else as soon as we can. We also should add a link to slayersonline website as this material came from the game.

**Comment by Nemikolh** [comment]
We already have a file that says that : https://github.com/GreenPix/sarosa/blob/master/assets/README.md
Do you think it needs rewording? 
I will add the link to slayers online.

Thanks for the feedback!

**Comment by lthms** [comment]
Oh, my bad. I didn’t see it.

> For the duration of the development, they have been lent to GreenPix and thus could be removed at any time.

Have they? By who and when?

**Comment by Nemikolh** [comment]
I'm not sure, I have written that a while ago. Probably not? @Azamung What do you think?

Otherwise, I was thinking we could say something like:

> Those file are temporary and do not belong to GreenPix. They come from the previous
> version of the game and can be found [here](http://slayersonline.net/guide/listeskins0.html).
> They will be removed in the future once the assets infrastructure is in place.

Also, even when we get the assets infrastructure we will need to specify each asset license somehow and specify that people can't do whatever they want with it. I'm not sure exactly how we are going to do it but probably through an authentication mechanism of some sort.

**Comment by lthms** [comment]
> Those file are temporary and do not belong to GreenPix. They come from the previous
> version of the game and can be found here.
> They will be removed in the future once the assets infrastructure is in place.

LGTM

> Also, even when we get the assets infrastructure we will need to specify each asset license somehow and specify that people can't do whatever they want with 

One problem at a time. I think we will have plenty of time to discuss this matter.

**Comment by ghost** [comment]
I updated the readme to add a link as suggested. I think we can now merge.

**Comment by lthms** [comment]
LGTM.

**Comment by Nemikolh** [comment]
@Vaelden Thanks!

**Pull request merged**
